#Source: https://stackoverflow.com/questions/43696005/attributeerror-module-pandas-has-no-attribute-read-csv-python3-5
df = pd.read_csv('file.csv', encoding='utf-8')