# LExecutor: DO NOT INSTRUMENT

#Source: https://stackoverflow.com/questions/75298674/changes-in-column-table2-to-be-sum-on-table1-column-show-attribute-error-in-py
from lexecutor.Runtime import _n_
from lexecutor.Runtime import _a_
from lexecutor.Runtime import _c_
from lexecutor.Runtime import _l_
_c_(623729, _a_(623700, _n_(623699, "cur", lambda: cur), "execute"), "Update custprodt, product set name1=? ,price1=?, quant1=? , remcont1=quant=?  where cpid=? , pid=? ",(_c_(623704, _a_(623703, _a_(623702, _n_(623701, "self", lambda: self), "var_pname"), "get")),_c_(623708, _a_(623707, _a_(623706, _n_(623705, "self", lambda: self), "var_price"), "get")),_c_(623712, _a_(623711, _a_(623710, _n_(623709, "self", lambda: self), "var_qty"), "get")),_c_(623716, _a_(623715, _a_(623714, _n_(623713, "self", lambda: self), "var_updatevalue"), "get"))== _c_(623720, _a_(623719, _a_(623718, _n_(623717, "self", lambda: self), "var_qunt"), "get")),_c_(623724, _a_(623723, _a_(623722, _n_(623721, "self", lambda: self), "var_cpid"), "get")),_c_(623728, _a_(623727, _a_(623726, _n_(623725, "self", lambda: self), "var_pid"), "get")),))
_l_(623730)